#!/bin/bash

AUTOCONF_WARNINGS=${AUTOCONF_WARNINGS:-none}
UPDATE_SUBMODULES=conf/update_submodules.sh

[ -f ${UPDATE_SUBMODULES} ] && . ${UPDATE_SUBMODULES} || exit 1

if [ -d conf/kconfig ]; then
 pushd conf/kconfig
 ./bootstrap
 popd
fi

aclocal -I ./conf/m4 -W ${AUTOCONF_WARNINGS}
autoheader
# libtoolize -c
automake --add-missing --copy -W ${AUTOCONF_WARNINGS}
autoconf



